name: Bug Report
description: 提交一个缺陷报告
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: 问题描述
      description: 说明现象、预期行为与影响范围
    validations:
      required: true
  - type: textarea
    id: task
    attributes:
      label: 任务输入与复现步骤
      description: 包含 `--task` 输入、关键日志、触发条件
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: 运行环境
      description: OS、Python、模型配置、API Provider
