name: Feature Request
description: 提交一个功能建议
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: scenario
    attributes:
      label: 使用场景
      description: 建议优先描述真实任务链路
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 方案与验收标准
      description: 期望交付、可衡量指标、兼容性影响
    validations:
      required: true
